module.exports = ZodiacCalc = {
  "Aquarius": {
       "Aquarius": 74,
       "Aries": 68,
       "Cancer": 31,
       "Capricorn": 37,
       "Gemini": 85,
       "Leo": 89,
       "Libra": 68,
       "Pisces": 38,
       "Sagittarius": 83,
       "Scorpio": 30,
       "Taurus": 11,
       "Virgo": 30
  },
  "Aries": {
       "Aquarius": 68,
       "Aries": 75,
       "Cancer": 47,
       "Capricorn": 38,
       "Gemini": 74,
       "Leo": 42,
       "Libra": 62,
       "Pisces": 29.,
       "Sagittarius": 87,
       "Scorpio": 48,
       "Taurus": 63,
       "Virgo": 42
  },
  "Cancer": {
       "Aquarius": 31,
       "Aries": 47,
       "Cancer": 85,
       "Capricorn": 84,
       "Gemini": 21,
       "Leo": 29.,
       "Libra": 28.,
       "Pisces": 72,
       "Sagittarius": 27,
       "Scorpio": 79,
       "Taurus": 91,
       "Virgo": 77
  },
  "Capricorn": {
       "Aquarius": 37,
       "Aries": 38,
       "Cancer": 84,
       "Capricorn": 62,
       "Gemini": 15,
       "Leo": 27,
       "Libra": 34,
       "Pisces": 76,
       "Sagittarius": 38,
       "Scorpio": 64,
       "Taurus": 89,
       "Virgo": 77
  },
  "Gemini":{
       "Aquarius": 85,
       "Aries": 74,
       "Cancer": 21,
       "Capricorn": 15,
       "Gemini": 83,
       "Leo": 82,
       "Libra": 78,
       "Pisces": 10,
       "Sagittarius": 92,
       "Scorpio": 15,
       "Taurus": 23,
       "Virgo": 40

  },
  "Leo": {
   "Aquarius": 89,
   "Aries": 42,
   "Cancer": 29,
   "Capricorn": 27,
   "Gemini": 82,
   "Leo": 78,
   "Libra": 75,
   "Pisces": 14,
   "Sagittarius": 75,
   "Scorpio": 29,
   "Taurus": 29,
   "Virgo": 35

  },
  "Libra": {
       "Aquarius": 68,
       "Aries": 62,
       "Cancer": 28,
       "Capricorn": 34,
       "Gemini": 78,
       "Leo": 75,
       "Libra": 68,
       "Pisces": 29,
       "Sagittarius": 71,
       "Scorpio": 29,
       "Taurus": 33,
       "Virgo": 30
  },
  "Pisces":{
       "Aquarius": 38,
       "Aries": 29,
       "Cancer": 72,
       "Capricorn": 76,
       "Gemini": 10,
       "Leo": 14,
       "Libra": 29,
       "Pisces": 73,
       "Sagittarius": 50,
       "Scorpio": 81,
       "Taurus": 88,
       "Virgo": 86
  },
  "Sagittarius":{
       "Aquarius": 83,
       "Aries": 87,
       "Cancer": 27,
       "Capricorn": 38,
       "Gemini": 92,
       "Leo": 75,
       "Libra": 71,
       "Pisces": 50,
       "Sagittarius": 74,
       "Scorpio": 30,
       "Taurus": 31,
       "Virgo": 32
  },
  "Scorpio": {
       "Aquarius": 30,
       "Aries": 48,
       "Cancer": 79,
       "Capricorn": 64,
       "Gemini": 15,
       "Leo": 29,
       "Libra": 29,
       "Pisces": 81,
       "Sagittarius": 30,
       "Scorpio": 66,
       "Taurus": 89,
       "Virgo": 76
  },
  "Taurus": {
       "Aquarius": 11,
       "Aries": 63,
       "Cancer": 91,
       "Capricorn": 89,
       "Gemini": 23,
       "Leo": 29,
       "Libra": 33,
       "Pisces": 88,
       "Sagittarius": 31,
       "Scorpio": 89,
       "Taurus": 86,
       "Virgo": 73
  },
  "Virgo": {
       "Aquarius": 30,
       "Aries": 42,
       "Cancer": 77,
       "Capricorn": 77,
       "Gemini": 40,
       "Leo": 35,
       "Libra": 30,
       "Pisces": 86,
       "Sagittarius": 32,
       "Scorpio": 76,
       "Taurus": 73,
       "Virgo": 65
  }   
};